name: Upload Python Package

on:
  release:
    types: [published]
  push:
    tags:
      - 'v*'          # triggers on tag push like v0.1.0
  workflow_dispatch:   # manual run button in Actions tab

permissions:
  contents: read

jobs:
  release-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"
      - name: Build release distributions
        run: |
          set -euxo pipefail
          python -m pip install -U pip build
          python -m build
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: release-dists
          path: dist/

  pypi-publish:
    runs-on: ubuntu-latest
    needs: [release-build]
    permissions:
      id-token: write
      contents: read
    # If this environment has reviewers, job will wait for approval.
    # Remove environment block while debugging if needed.
    # environment:
    #   name: pypi
    #   url: https://pypi.org/p/eigen-robotics
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: release-dists
          path: dist/
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: dist/
          skip-existing: true
          verbose: true
